<div class="content">
    <footer id="myFooter">
        		        
        <div class="footer-copyright">
            <p><h5>© Copyright - LINFOX</h5></p>
			
        </div>
		
		
<style>
		#myFooter {
	background-color: #373a48;
	color:white;
}

#myFooter .footer-copyright{
	background-color: #383737;
	padding-top:1px;
	padding-bottom:1px;
	text-align: center;
}

#myFooter .footer-copyright p{
	margin:10px;
	color: #ccc;
}


#myFooter h5{
	font-size: 18px;
    color: white;
    font-weight: bold;
    margin-top: 20px;
}

#myFooter a{
	color:#d2d1d1;
	text-decoration: none;
}

#myFooter a:hover, #myFooter a:focus{
	text-decoration: none;
	color:white;
}

#myFooter .myCols{
	text-align: center;
}

#myFooter .social-networks{
	text-align: center;
	padding-top: 2px;
	padding-bottom: 2px;
}

#myFooter .social-networks a{
    font-size: 22px;
    margin-right: 5px;
    margin-left: 5px;
    color: #f9f9f9;
    padding: 2px;
    transition: 0.2s;
}

#myFooter .social-networks a:hover{
	text-decoration: none;

}

#myFooter .facebook:hover{
	color:#0077e2;
}

#myFooter .google:hover{
	color:#ef1a1a;
}

#myFooter .twitter:hover{
	color: #00aced;
}

@media screen and (max-width: 767px){
	#myFooter {
		text-align: center;
	}
}

html{
	height: 100% !important;
}





.content{
	flex: 1 0 auto;
	-webkit-flex: 1 0 auto;
	min-height: 100px;
}

#myFooter{
	flex: 0 0 auto;
    -webkit-flex: 0 0 auto;
}
</style>
</div>


